@startuml
|User|
start




|#AntiqueWhite|System|
|User|
:Create user;
:Log in;
:Request carport;

|System|
:Register request;
:Create BOM;
:Create SVG sketch of carport;
:Calculate estimed price;
|User|
:Customer gains access to a sketch and an estimated price;
|Admin|
:Read request;
:Contact customer if needed;
:Set final price for the order;
|User|
:Pay for carport;
|System|
:Recieve payment;
|Admin|
:Update status;

|System|
:Makes BOM visible to the customer;


|User|
:Retrieve carport;
stop
@enduml